# Generated by Django 4.0.6 on 2022-07-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaccount',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
