# Generated by Django 4.0.4 on 2022-05-11 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_friend_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
