# Generated by Django 4.0.4 on 2022-05-12 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wishlist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='phone_number',
            field=models.CharField(blank=True, default=2349005044, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
