# Generated by Django 4.0.6 on 2022-07-31 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cart_id_remove_wishlist_id_alter_cart_user_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='cart',
        #     name='user',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='wishlist',
        #     name='user',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        # ),
    ]
