# Generated by Django 4.0.4 on 2022-05-16 12:30

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customaccount_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbers', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='customaccount',
            name='address',
            field=models.ForeignKey(blank=True, default='3, Korede Ase Street', on_delete=django.db.models.deletion.CASCADE, to='accounts.addressbook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customaccount',
            name='phone_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.phonebook'),
        ),
    ]
