# Generated by Django 4.0.6 on 2022-07-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cart_user_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.cart'),
        ),
    ]
