# Generated by Django 4.0.6 on 2022-07-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_cartdetails_id_alter_cartdetails_cart'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='cart',
        #     name='cart_products',
        # ),
        # migrations.RemoveField(
        #     model_name='cartdetails',
        #     name='cart',
        # ),
        # migrations.AddField(
        #     model_name='cartdetails',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
