# Generated by Django 4.0.4 on 2022-05-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_addressbook_phonebook_alter_cartdetails_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaccount',
            name='address',
        ),
        migrations.DeleteModel(
            name='AddressBook',
        ),
    ]
