# Generated by Django 4.0.4 on 2022-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customaccount_phone_number_delete_phonebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaccount',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
