# Generated by Django 4.0.4 on 2022-05-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customaccount_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wish_products',
        ),
    ]
