# Generated by Django 4.0.6 on 2022-07-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_wishlist_id_wishlist_user'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wishlist',
        #     name='user',
        # ),
    ]
