# Generated by Django 4.0.4 on 2022-05-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wishlist_wish_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaccount',
            name='is_vendor',
        ),
    ]
