# Generated by Django 4.0.6 on 2022-07-31 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cart_cartdetails_wishlist_cart_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cart'),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
