# Generated by Django 3.2.15 on 2022-08-05 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userprofile_city_alter_userprofile_postcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customaccount')),
                ('total', models.IntegerField()),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Delivered', 'Completed'), ('In Progress', 'In Progress'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTickets',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customaccount')),
                ('subject', models.CharField(max_length=250)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_type', models.CharField(choices=[('Website Issues', 'Website Issues'), ('Complaint', 'Complaint'), ('Inquiry', 'Inquiry'), ('Order Issues', 'Order Issues')], max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
