# Generated by Django 3.2.15 on 2022-08-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220805_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='order_number',
            field=models.CharField(default='UI091L4CZG55', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
