# Generated by Django 3.2.15 on 2022-08-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userorders_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaccount',
            name='address',
        ),
    ]
