# Generated by Django 3.2.15 on 2022-08-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_customaccount_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaccount',
            name='username',
        ),
    ]
