PHONE_MANUFACTURER_CHOICES = [
    ('SAMSUNG', 'SAMSUNG'),
    ('ACER', 'ACER'),
    ('ALCATEL', 'ALCATEL'),
    ('ALLVIEW', 'ALLVIEW'),
    ('AMAZON', 'AMAZON'),
    ('AMOI', 'AMOI'),
    ('APPLE', 'APPLE'),
    ('ARCHOS', 'ARCHOS'),
    ('ASUS', 'ASUS'),
    ('AT&T', 'AT&T'),
    ('BENEFON', 'BENEFON'),
    ('BENQ', 'BENQ'),
    ('BENQ-SIEMENS', 'BENQ-SIEMENS'),
    ('BIRD', 'BIRD'),
    ('BLACKBERRY', 'BLACKBERRY'),
    ('BLACKVIEW', 'BLACKVIEW'),
    ('BLU', 'BLU'),
    ('BOSCH', 'BOSCH'),
    ('BQ', 'BQ'),
    ('CASIO', 'CASIO'),
    ('CELKON', 'CELKON'),
    ('CHEA', 'CHEA'),
    ('COOLPAD', 'COOLPAD'),
    ('DELL', 'DELL'),
    ('EMPORIA', 'EMPORIA'),
    ('ENERGIZER', 'ENERGIZER'),
    ('ERICSSON', 'ERICSSON'),
    ('ETEN', 'ETEN'),
    ('FAIRPHONE', 'FAIRPHONE'),
    ('FUJITSU SIEMENS', 'FUJITSU SIEMENS'),
    ('GARMIN-ASUS', 'GARMIN-ASUS'),
    ('GIGABYTE', 'GIGABYTE'),
    ('GIONEE', 'GIONEE'),
    ('GOOGLE', 'GOOGLE'),
    ('HAIER', 'HAIER'),
    ('HONOR', 'HONOR'),
    ('HP', 'HP'),
    ('HTC', 'HTC'),
    ('HUAWEI', 'HUAWEI'),
    ('I-MATE', 'I-MATE'),
    ('I-MOBILE', 'I-MOBILE'),
    ('ICEMOBILE', 'ICEMOBILE'),
    ('INFINIX', 'INFINIX'),
    ('INNOSTREAM', 'INNOSTREAM'),
    ('INQ', 'INQ'),
    ('INTEX', 'INTEX'),
    ('JOLLA', 'JOLLA'),
    ('KARBONN', 'KARBONN'),
    ('KYOCERA', 'KYOCERA'),
    ('LAVA', 'LAVA'),
    ('LEECO', 'LEECO'),
    ('LENOVO', 'LENOVO'),
    ('LG', 'LG'),
    ('MAXON', 'MAXON'),
    ('MAXWEST', 'MAXWEST'),
    ('MEIZU', 'MEIZU'),
    ('MICROMAX', 'MICROMAX'),
    ('MICROSOFT', 'MICROSOFT'),
    ('MITAC', 'MITAC'),
    ('MITSUBISHI', 'MITSUBISHI'),
    ('MODU', 'MODU'),
    ('MOTOROLA', 'MOTOROLA'),
    ('MWG', 'MWG'),
    ('NEC', 'NEC'),
    ('NEONODE', 'NEONODE'),
    ('NIU', 'NIU'),
    ('NOKIA', 'NOKIA'),
    ('NVIDIA', 'NVIDIA'),
    ('O2', 'O2'),
    ('ONEPLUS', 'ONEPLUS'),
    ('OPPO', 'OPPO'),
    ('ORANGE', 'ORANGE'),
    ('PALM', 'PALM'),
    ('PANASONIC', 'PANASONIC'),
    ('PANTECH', 'PANTECH'),
    ('PARLA', 'PARLA'),
    ('PHILIPS', 'PHILIPS'),
    ('PLUM', 'PLUM'),
    ('POSH', 'POSH'),
    ('PRESTIGIO', 'PRESTIGIO'),
    ('QMOBILE', 'QMOBILE'),
    ('QTEK', 'QTEK'),
    ('RAZER', 'RAZER'),
    ('REALME', 'REALME'),
    ('SAGEM', 'SAGEM'),
    ('SENDO', 'SENDO'),
    ('SEWON', 'SEWON'),
    ('SHARP', 'SHARP'),
    ('SIEMENS', 'SIEMENS'),
    ('SONIM', 'SONIM'),
    ('SONY', 'SONY'),
    ('SONY ERICSSON', 'SONY ERICSSON'),
    ('SPICE', 'SPICE'),
    ('T-MOBILE', 'T-MOBILE'),
    ('TCL', 'TCL'),
    ('TECNO', 'TECNO'),
    ('TEL.ME.', 'TEL.ME.'),
    ('TELIT', 'TELIT'),
    ('THURAYA', 'THURAYA'),
    ('TOSHIBA', 'TOSHIBA'),
    ('ULEFONE', 'ULEFONE'),
    ('UNNECTO', 'UNNECTO'),
    ('VERTU', 'VERTU'),
    ('VERYKOOL', 'VERYKOOL'),
    ('VIVO', 'VIVO'),
    ('VK MOBILE', 'VK MOBILE'),
    ('VODAPHONE', 'VODAPHONE'),
    ('WIKO', 'WIKO'),
    ('WND', 'WND'),
    ('XCUTE', 'XCUTE'),
    ('XIAOMI', 'XIAOMI'),
    ('XOLO', 'XOLO'),
    ('YEZZ', 'YEZZ'),
    ('YOTA', 'YOTA'),
    ('YU', 'YU'),
    ('ZTE', 'ZTE'),
]

PHONE_OS_CHOICES = [
    ('Android', 'Android'),
    ('iOS', 'iOS'),
    ('Blackberry OS', 'Blackberry OS'),
    ('Windows OS', 'Windows OS'),
]

PC_OS_CHOICES = [
    ('Linux', 'Linux'),
    ('macOS', 'macOS'),
    ('Windows OS', 'Windows OS'),
]

PC_MANUFACTURER_CHOICES = [
    ('AORUS', 'AORUS'),
    ('HP', 'HP'),
    ('LENOVO', 'LENOVO'),
    ('MSI', 'MSI'),
    ('ASUS', 'ASUS'),
    ('DELL', 'DELL'),
    ('ACER', 'ACER'),
    ('GIGABYTE', 'GIGABYTE'),
    ('MICROSOFT', 'MICROSOFT'),
    ('ALIENWARE', 'ALIENWARE'),
    ('APPLE', 'APPLE'),
    ('RAZER', 'RAZER'),
    ('SAMSUNG', 'SAMSUNG'),
    ('LG', 'LG'),
    ('TOSHIBA', 'TOSHIBA'),
    ('FUJITSU', 'FUJITSU'),
    ('PANASONIC', 'PANASONIC'),
    ('HUAWEI', 'HUAWEI'),
    ('DYNABOOK', 'DYNABOOK'),
    ('LAPTOPMEDIA', 'LAPTOPMEDIA'),
    ('INFINIX', 'INFINIX'),
    ('XIAOMI', 'XIAOMI'),
    ('SONY', 'SONY'),
    ('TOSHIBA', 'TOSHIBA'),
    ('DURABOOK', 'DURABOOK'),
    ('GOOGLE', 'GOOGLE'),
    ('NOKIA', 'NOKIA'),
    ('VAIO', 'VAIO'),
    ('PACKARD BELL', 'PACKARD BELL'),
    ('MSi', 'MSi'),
    ('HYUNDAI TECHNOLOGY', 'HYUNDAI TECHNOLOGY'),
    ('PREDATOR', 'PREDATOR'),
]

GAME_OS_CHOICES = [
    ('Linux', 'Linux'),
    ('macOS', 'macOS'),
    ('Windows 10', 'Windows 10'),
    ('Windows 7', 'Windows 7'),
    ('Windows 8', 'Windows 8'),
    ('Windows Vista', 'Windows Vista'),
]

SIM_SLOT_CHOICES =  [
    ('Single Sim', 'Single Sim'),
    ('Dual Sim', 'Dual Sim')
]

NETWORK_CHOICES = [
    ('2G', '2G'),
    ('3G', '3G'),
    ('4G', '4G'),
    ('5G', '5G')
]

HARD_DISK_CHOICES = [
    ('SSD', 'SSD'),
    ('HDD', 'HDD')
]

PROCESSOR_TYPE_CHOICES = [
    ('64-Bit', '64-Bit'),
    ('32-Bit', '32-Bit')
]

PHONE = 'PHONE'
PC = 'PC'
REFURBISHED = 'REFURBISHED'
GAMES = 'GAME'
# ACCESSORIES = 'ACCESSORY'
# APPLIANCES = 'APPLIANCE'

PRODUCT_CHOICES = [
    (PHONE, 'PHONE'),
    (PC, 'LAPTOP'),
    (GAMES, 'VIDEO GAME'),
    (REFURBISHED, 'REFURBISHED PRODUCT'),
    # (ACCESSORIES, 'TECH ACCESSORY'),
    # (APPLIANCES, 'OFFICE APPLIANCE'),
]