# Generated by Django 4.0.6 on 2022-07-28 04:52

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, blank=True, max_length=300)),
                ('name', models.CharField(help_text='Name of Product', max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='products_images/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.PositiveIntegerField()),
                ('previous_price', models.PositiveIntegerField(blank=True, default=0)),
                ('percent_off', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('PHONE', 'PHONE'), ('PC', 'LAPTOP'), ('REFURBISHED', 'REFURBISHED PRODUCT'), ('ACCESSORY', 'TECH ACCESSORY'), ('APPLIANCE', 'OFFICE APPLIANCE'), ('GAME', 'VIDEO GAME')], default='PC', max_length=100)),
                ('category_url', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_info', serialize=False, to='products.product')),
                ('min_ram', models.IntegerField()),
                ('developers', models.CharField(max_length=80)),
                ('recom_ram', models.IntegerField()),
                ('min_processor', models.CharField(max_length=100)),
                ('recom_processor', models.CharField(max_length=100)),
                ('processor_type', models.CharField(choices=[('64-Bit', '64-Bit'), ('32-Bit', '32-Bit')], max_length=20)),
                ('min_storage', models.IntegerField()),
                ('recom_storage', models.IntegerField()),
                ('os_type', models.CharField(choices=[('Linux', 'Linux'), ('macOS', 'macOS'), ('Windows 10', 'Windows 10'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows Vista', 'Windows Vista')], max_length=50)),
                ('min_dx_version', models.IntegerField()),
                ('recom_dx_version', models.IntegerField()),
                ('size', models.IntegerField()),
                ('min_graphics_card', models.CharField(max_length=130)),
                ('recom_graphics_card', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pc_info', serialize=False, to='products.product')),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('manufacturer', models.CharField(choices=[('AORUS', 'AORUS'), ('HP', 'HP'), ('LENOVO', 'LENOVO'), ('MSI', 'MSI'), ('ASUS', 'ASUS'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('GIGABYTE', 'GIGABYTE'), ('MICROSOFT', 'MICROSOFT'), ('ALIENWARE', 'ALIENWARE'), ('APPLE', 'APPLE'), ('RAZER', 'RAZER'), ('SAMSUNG', 'SAMSUNG'), ('LG', 'LG'), ('TOSHIBA', 'TOSHIBA'), ('FUJITSU', 'FUJITSU'), ('PANASONIC', 'PANASONIC'), ('HUAWEI', 'HUAWEI'), ('DYNABOOK', 'DYNABOOK'), ('LAPTOPMEDIA', 'LAPTOPMEDIA'), ('INFINIX', 'INFINIX'), ('XIAOMI', 'XIAOMI'), ('SONY', 'SONY'), ('TOSHIBA', 'TOSHIBA'), ('DURABOOK', 'DURABOOK'), ('GOOGLE', 'GOOGLE'), ('NOKIA', 'NOKIA'), ('VAIO', 'VAIO'), ('PACKARD BELL', 'PACKARD BELL'), ('MSi', 'MSi'), ('HYUNDAI TECHNOLOGY', 'HYUNDAI TECHNOLOGY'), ('PREDATOR', 'PREDATOR')], default='SAMSUNG', max_length=60)),
                ('model', models.CharField(max_length=100)),
                ('graphics_card', models.CharField(max_length=150)),
                ('hard_disk', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=25)),
                ('weight', models.CharField(max_length=40)),
                ('screen_size', models.FloatField()),
                ('resolution', models.CharField(max_length=40)),
                ('os_type', models.CharField(choices=[('Linux', 'Linux'), ('macOS', 'macOS'), ('Windows OS', 'Windows OS')], max_length=50)),
                ('os_version', models.FloatField()),
                ('cpu', models.CharField(max_length=120)),
                ('motherboard', models.CharField(max_length=120)),
                ('battery', models.IntegerField()),
                ('bluetooth', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('hotspot', models.BooleanField()),
                ('fingerprint', models.BooleanField()),
                ('face_unlock', models.BooleanField()),
                ('processor', models.CharField(max_length=100)),
                ('processor_type', models.CharField(choices=[('64-Bit', '64-Bit'), ('32-Bit', '32-Bit')], max_length=20)),
                ('network', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], max_length=10)),
                ('sd_card_slot', models.BooleanField()),
                ('water_proof', models.BooleanField()),
                ('water_resistant', models.BooleanField()),
                ('dust_resistant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone_info', serialize=False, to='products.product')),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('manufacturer', models.CharField(choices=[('SAMSUNG', 'SAMSUNG'), ('ACER', 'ACER'), ('ALCATEL', 'ALCATEL'), ('ALLVIEW', 'ALLVIEW'), ('AMAZON', 'AMAZON'), ('AMOI', 'AMOI'), ('APPLE', 'APPLE'), ('ARCHOS', 'ARCHOS'), ('ASUS', 'ASUS'), ('AT&T', 'AT&T'), ('BENEFON', 'BENEFON'), ('BENQ', 'BENQ'), ('BENQ-SIEMENS', 'BENQ-SIEMENS'), ('BIRD', 'BIRD'), ('BLACKBERRY', 'BLACKBERRY'), ('BLACKVIEW', 'BLACKVIEW'), ('BLU', 'BLU'), ('BOSCH', 'BOSCH'), ('BQ', 'BQ'), ('CASIO', 'CASIO'), ('CELKON', 'CELKON'), ('CHEA', 'CHEA'), ('COOLPAD', 'COOLPAD'), ('DELL', 'DELL'), ('EMPORIA', 'EMPORIA'), ('ENERGIZER', 'ENERGIZER'), ('ERICSSON', 'ERICSSON'), ('ETEN', 'ETEN'), ('FAIRPHONE', 'FAIRPHONE'), ('FUJITSU SIEMENS', 'FUJITSU SIEMENS'), ('GARMIN-ASUS', 'GARMIN-ASUS'), ('GIGABYTE', 'GIGABYTE'), ('GIONEE', 'GIONEE'), ('GOOGLE', 'GOOGLE'), ('HAIER', 'HAIER'), ('HONOR', 'HONOR'), ('HP', 'HP'), ('HTC', 'HTC'), ('HUAWEI', 'HUAWEI'), ('I-MATE', 'I-MATE'), ('I-MOBILE', 'I-MOBILE'), ('ICEMOBILE', 'ICEMOBILE'), ('INFINIX', 'INFINIX'), ('INNOSTREAM', 'INNOSTREAM'), ('INQ', 'INQ'), ('INTEX', 'INTEX'), ('JOLLA', 'JOLLA'), ('KARBONN', 'KARBONN'), ('KYOCERA', 'KYOCERA'), ('LAVA', 'LAVA'), ('LEECO', 'LEECO'), ('LENOVO', 'LENOVO'), ('LG', 'LG'), ('MAXON', 'MAXON'), ('MAXWEST', 'MAXWEST'), ('MEIZU', 'MEIZU'), ('MICROMAX', 'MICROMAX'), ('MICROSOFT', 'MICROSOFT'), ('MITAC', 'MITAC'), ('MITSUBISHI', 'MITSUBISHI'), ('MODU', 'MODU'), ('MOTOROLA', 'MOTOROLA'), ('MWG', 'MWG'), ('NEC', 'NEC'), ('NEONODE', 'NEONODE'), ('NIU', 'NIU'), ('NOKIA', 'NOKIA'), ('NVIDIA', 'NVIDIA'), ('O2', 'O2'), ('ONEPLUS', 'ONEPLUS'), ('OPPO', 'OPPO'), ('ORANGE', 'ORANGE'), ('PALM', 'PALM'), ('PANASONIC', 'PANASONIC'), ('PANTECH', 'PANTECH'), ('PARLA', 'PARLA'), ('PHILIPS', 'PHILIPS'), ('PLUM', 'PLUM'), ('POSH', 'POSH'), ('PRESTIGIO', 'PRESTIGIO'), ('QMOBILE', 'QMOBILE'), ('QTEK', 'QTEK'), ('RAZER', 'RAZER'), ('REALME', 'REALME'), ('SAGEM', 'SAGEM'), ('SENDO', 'SENDO'), ('SEWON', 'SEWON'), ('SHARP', 'SHARP'), ('SIEMENS', 'SIEMENS'), ('SONIM', 'SONIM'), ('SONY', 'SONY'), ('SONY ERICSSON', 'SONY ERICSSON'), ('SPICE', 'SPICE'), ('T-MOBILE', 'T-MOBILE'), ('TCL', 'TCL'), ('TECNO', 'TECNO'), ('TEL.ME.', 'TEL.ME.'), ('TELIT', 'TELIT'), ('THURAYA', 'THURAYA'), ('TOSHIBA', 'TOSHIBA'), ('ULEFONE', 'ULEFONE'), ('UNNECTO', 'UNNECTO'), ('VERTU', 'VERTU'), ('VERYKOOL', 'VERYKOOL'), ('VIVO', 'VIVO'), ('VK MOBILE', 'VK MOBILE'), ('VODAPHONE', 'VODAPHONE'), ('WIKO', 'WIKO'), ('WND', 'WND'), ('XCUTE', 'XCUTE'), ('XIAOMI', 'XIAOMI'), ('XOLO', 'XOLO'), ('YEZZ', 'YEZZ'), ('YOTA', 'YOTA'), ('YU', 'YU'), ('ZTE', 'ZTE')], default='SAMSUNG', max_length=60)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('screen_size', models.FloatField()),
                ('resolution', models.CharField(max_length=40)),
                ('os_type', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Blackberry OS', 'Blackberry OS'), ('Windows OS', 'Windows OS')], max_length=50)),
                ('os_version', models.FloatField()),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('sim_slots', models.CharField(choices=[('Single Sim', 'Single Sim'), ('Dual Sim', 'Dual Sim')], max_length=50)),
                ('front_camera', models.IntegerField()),
                ('back_camera', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('bluetooth', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('hotspot', models.BooleanField()),
                ('fingerprint', models.BooleanField()),
                ('face_unlock', models.BooleanField()),
                ('accelerometer', models.BooleanField()),
                ('gyro', models.BooleanField()),
                ('compass', models.BooleanField()),
                ('network', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], max_length=10)),
                ('sd_card', models.BooleanField()),
                ('water_proof', models.BooleanField()),
                ('water_resistant', models.BooleanField()),
                ('dust_resistant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_title', models.CharField(max_length=150)),
                ('review', ckeditor_uploader.fields.RichTextUploadingField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoreProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all_product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['content_type', 'object_id'], name='products_pr_content_7286c1_idx'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gamegenres'),
        ),
    ]
