# Generated by Django 4.0.6 on 2022-07-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('PC', 'LAPTOP'), ('GAME', 'VIDEO GAME'), ('REFURBISHED', 'REFURBISHED PRODUCT')], default='PC', max_length=100),
        ),
    ]
