# Generated by Django 4.0.4 on 2022-05-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
