# Generated by Django 4.0.4 on 2022-05-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='previous_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
