# Generated by Django 4.0.4 on 2022-05-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_previous_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_info', serialize=False, to='products.product')),
                ('min_ram', models.IntegerField()),
                ('max_ram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pc_info', serialize=False, to='products.product')),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('manufacturer', models.CharField(choices=[('AORUS', 'AORUS'), ('HP', 'HP'), ('LENOVO', 'LENOVO'), ('MSI', 'MSI'), ('ASUS', 'ASUS'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('GIGABYTE', 'GIGABYTE'), ('MICROSOFT', 'MICROSOFT'), ('ALIENWARE', 'ALIENWARE'), ('APPLE', 'APPLE'), ('RAZER', 'RAZER'), ('SAMSUNG', 'SAMSUNG'), ('LG', 'LG'), ('TOSHIBA', 'TOSHIBA'), ('FUJITSU', 'FUJITSU'), ('PANASONIC', 'PANASONIC'), ('HUAWEI', 'HUAWEI'), ('DYNABOOK', 'DYNABOOK'), ('LAPTOPMEDIA', 'LAPTOPMEDIA'), ('INFINIX', 'INFINIX'), ('XIAOMI', 'XIAOMI'), ('SONY', 'SONY'), ('TOSHIBA', 'TOSHIBA'), ('DURABOOK', 'DURABOOK'), ('GOOGLE', 'GOOGLE'), ('NOKIA', 'NOKIA'), ('VAIO', 'VAIO'), ('PACKARD BELL', 'PACKARD BELL'), ('MSi', 'MSi'), ('HYUNDAI TECHNOLOGY', 'HYUNDAI TECHNOLOGY')], default='SAMSUNG', max_length=60)),
                ('model', models.CharField(max_length=100)),
                ('graphics_card', models.CharField(max_length=150)),
                ('hard_disk', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=25)),
                ('weight', models.CharField(max_length=40)),
                ('screen_size', models.FloatField()),
                ('resolution', models.CharField(max_length=40)),
                ('os_type', models.CharField(choices=[('Linux', 'Linux'), ('macOS', 'macOS'), ('Windows OS', 'Windows OS')], max_length=50)),
                ('os_version', models.FloatField()),
                ('cpu', models.CharField(max_length=120)),
                ('motherboard', models.CharField(max_length=120)),
                ('battery', models.IntegerField()),
                ('bluetooth', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('hotspot', models.BooleanField()),
                ('fingerprint', models.BooleanField()),
                ('face_unlock', models.BooleanField()),
                ('processor', models.CharField(max_length=100)),
                ('processor_type', models.CharField(choices=[('64-Bit', '64-Bit'), ('32-Bit', '32-Bit')], max_length=20)),
                ('network', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], max_length=10)),
                ('sd_card_slot', models.BooleanField()),
                ('water_proof', models.BooleanField()),
                ('water_resistant', models.BooleanField()),
                ('dust_resistant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone_info', serialize=False, to='products.product')),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('manufacturer', models.CharField(choices=[('SAMSUNG', 'SAMSUNG'), ('ACER', 'ACER'), ('ALCATEL', 'ALCATEL'), ('ALLVIEW', 'ALLVIEW'), ('AMAZON', 'AMAZON'), ('AMOI', 'AMOI'), ('APPLE', 'APPLE'), ('ARCHOS', 'ARCHOS'), ('ASUS', 'ASUS'), ('AT&T', 'AT&T'), ('BENEFON', 'BENEFON'), ('BENQ', 'BENQ'), ('BENQ-SIEMENS', 'BENQ-SIEMENS'), ('BIRD', 'BIRD'), ('BLACKBERRY', 'BLACKBERRY'), ('BLACKVIEW', 'BLACKVIEW'), ('BLU', 'BLU'), ('BOSCH', 'BOSCH'), ('BQ', 'BQ'), ('CASIO', 'CASIO'), ('CELKON', 'CELKON'), ('CHEA', 'CHEA'), ('COOLPAD', 'COOLPAD'), ('DELL', 'DELL'), ('EMPORIA', 'EMPORIA'), ('ENERGIZER', 'ENERGIZER'), ('ERICSSON', 'ERICSSON'), ('ETEN', 'ETEN'), ('FAIRPHONE', 'FAIRPHONE'), ('FUJITSU SIEMENS', 'FUJITSU SIEMENS'), ('GARMIN-ASUS', 'GARMIN-ASUS'), ('GIGABYTE', 'GIGABYTE'), ('GIONEE', 'GIONEE'), ('GOOGLE', 'GOOGLE'), ('HAIER', 'HAIER'), ('HONOR', 'HONOR'), ('HP', 'HP'), ('HTC', 'HTC'), ('HUAWEI', 'HUAWEI'), ('I-MATE', 'I-MATE'), ('I-MOBILE', 'I-MOBILE'), ('ICEMOBILE', 'ICEMOBILE'), ('INFINIX', 'INFINIX'), ('INNOSTREAM', 'INNOSTREAM'), ('INQ', 'INQ'), ('INTEX', 'INTEX'), ('JOLLA', 'JOLLA'), ('KARBONN', 'KARBONN'), ('KYOCERA', 'KYOCERA'), ('LAVA', 'LAVA'), ('LEECO', 'LEECO'), ('LENOVO', 'LENOVO'), ('LG', 'LG'), ('MAXON', 'MAXON'), ('MAXWEST', 'MAXWEST'), ('MEIZU', 'MEIZU'), ('MICROMAX', 'MICROMAX'), ('MICROSOFT', 'MICROSOFT'), ('MITAC', 'MITAC'), ('MITSUBISHI', 'MITSUBISHI'), ('MODU', 'MODU'), ('MOTOROLA', 'MOTOROLA'), ('MWG', 'MWG'), ('NEC', 'NEC'), ('NEONODE', 'NEONODE'), ('NIU', 'NIU'), ('NOKIA', 'NOKIA'), ('NVIDIA', 'NVIDIA'), ('O2', 'O2'), ('ONEPLUS', 'ONEPLUS'), ('OPPO', 'OPPO'), ('ORANGE', 'ORANGE'), ('PALM', 'PALM'), ('PANASONIC', 'PANASONIC'), ('PANTECH', 'PANTECH'), ('PARLA', 'PARLA'), ('PHILIPS', 'PHILIPS'), ('PLUM', 'PLUM'), ('POSH', 'POSH'), ('PRESTIGIO', 'PRESTIGIO'), ('QMOBILE', 'QMOBILE'), ('QTEK', 'QTEK'), ('RAZER', 'RAZER'), ('REALME', 'REALME'), ('SAGEM', 'SAGEM'), ('SENDO', 'SENDO'), ('SEWON', 'SEWON'), ('SHARP', 'SHARP'), ('SIEMENS', 'SIEMENS'), ('SONIM', 'SONIM'), ('SONY', 'SONY'), ('SONY ERICSSON', 'SONY ERICSSON'), ('SPICE', 'SPICE'), ('T-MOBILE', 'T-MOBILE'), ('TCL', 'TCL'), ('TECNO', 'TECNO'), ('TEL.ME.', 'TEL.ME.'), ('TELIT', 'TELIT'), ('THURAYA', 'THURAYA'), ('TOSHIBA', 'TOSHIBA'), ('ULEFONE', 'ULEFONE'), ('UNNECTO', 'UNNECTO'), ('VERTU', 'VERTU'), ('VERYKOOL', 'VERYKOOL'), ('VIVO', 'VIVO'), ('VK MOBILE', 'VK MOBILE'), ('VODAPHONE', 'VODAPHONE'), ('WIKO', 'WIKO'), ('WND', 'WND'), ('XCUTE', 'XCUTE'), ('XIAOMI', 'XIAOMI'), ('XOLO', 'XOLO'), ('YEZZ', 'YEZZ'), ('YOTA', 'YOTA'), ('YU', 'YU'), ('ZTE', 'ZTE')], default='SAMSUNG', max_length=60)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=40)),
                ('screen_size', models.FloatField()),
                ('resolution', models.CharField(max_length=40)),
                ('os_type', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Blackberry OS', 'Blackberry OS'), ('Windows OS', 'Windows OS')], max_length=50)),
                ('os_version', models.FloatField()),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('sim_slots', models.CharField(choices=[('Single Sim', 'Single Sim'), ('Dual Sim', 'Dual Sim')], max_length=50)),
                ('front_camera', models.IntegerField()),
                ('back_camera', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('bluetooth', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('hotspot', models.BooleanField()),
                ('fingerprint', models.BooleanField()),
                ('face_unlock', models.BooleanField()),
                ('accelerometer', models.BooleanField()),
                ('gyro', models.BooleanField()),
                ('compass', models.BooleanField()),
                ('network', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], max_length=10)),
                ('sd_card', models.BooleanField()),
                ('water_proof', models.BooleanField()),
                ('water_resistant', models.BooleanField()),
                ('dust_resistant', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHONE', 'PHONES'), ('LAPTOP', 'LAPTOPS'), ('REFURBISHED', 'REFURBISHED GOODS'), ('ACCESSORIES', 'TECH ACCESSORIES'), ('APPLIANCES', 'OFFICE APPLIANCES'), ('GAMES', 'VIDEO GAMES')], default='PHONE', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
