# Generated by Django 4.0.4 on 2022-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_game_pc_phone_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_ram',
        ),
        migrations.AddField(
            model_name='game',
            name='min_dx_version',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='min_processor',
            field=models.CharField(default='Intel Core i5', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='min_storage',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='os_type',
            field=models.CharField(choices=[('Linux', 'Linux'), ('macOS', 'macOS'), ('Windows 10', 'Windows 10'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows Vista', 'Windows Vista')], default='Windows 10', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='processor_type',
            field=models.CharField(choices=[('64-Bit', '64-Bit'), ('32-Bit', '32-Bit')], default='64-Bits', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='recom_dx_version',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='recom_processor',
            field=models.CharField(default='Intel Core i9', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='recom_ram',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='recom_storage',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
    ]
