# Generated by Django 4.0.4 on 2022-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_game_max_ram_game_min_dx_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
