# Generated by Django 4.0.4 on 2022-05-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_game_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.CharField(default='Rockstar', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='min_graphics_card',
            field=models.CharField(default='Intel Graphics 4000', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='recom_graphics_card',
            field=models.CharField(default='NVIDIA GeForce GTX90', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='weight',
            field=models.FloatField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of Product', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('PC', 'LAPTOP'), ('REFURBISHED', 'REFURBISHED PRODUCT'), ('ACCESSORY', 'TECH ACCESSORY'), ('APPLIANCE', 'OFFICE APPLIANCE'), ('GAME', 'VIDEO GAME')], max_length=100),
        ),
    ]
