# Generated by Django 4.0.4 on 2022-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_game_developers_game_min_graphics_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developers',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_graphics_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='recom_graphics_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='weight',
            field=models.FloatField(),
        ),
    ]
