# Generated by Django 4.0.4 on 2022-06-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='min_graphics_card',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recom_graphics_card',
        ),
    ]
