# Generated by Django 4.0.4 on 2022-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_game_min_graphics_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='min_graphics_card',
            field=models.CharField(default='Intel HD 4000', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='recom_graphics_card',
            field=models.CharField(default='NVIDIA GeForce 960 RTX', max_length=130),
            preserve_default=False,
        ),
    ]
