# Generated by Django 4.0.4 on 2022-07-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_category_products_ca_content_0b2c19_idx'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='product',
        #     name='category',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        # ),
    ]
