# Generated by Django 4.0.4 on 2022-07-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_category'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product',
        #     name='product_type',
        #     field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='product',
        #     name='category',
        #     field=models.CharField(choices=[('PHONE', 'PHONE'), ('PC', 'LAPTOP'), ('REFURBISHED', 'REFURBISHED PRODUCT'), ('ACCESSORY', 'TECH ACCESSORY'), ('APPLIANCE', 'OFFICE APPLIANCE'), ('GAME', 'VIDEO GAME')], max_length=100),
        # ),
    ]
