# Generated by Django 4.0.4 on 2022-07-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_product_type_alter_product_category'),
    ]

    operations = [
    #     migrations.RemoveField(
    #         model_name='product',
    #         name='category',
    #     ),
    #     migrations.RemoveField(
    #         model_name='product',
    #         name='product_type',
    #     ),
    ]
