# Generated by Django 4.0.4 on 2022-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_category_remove_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('PC', 'LAPTOP'), ('REFURBISHED', 'REFURBISHED PRODUCT'), ('ACCESSORY', 'TECH ACCESSORY'), ('APPLIANCE', 'OFFICE APPLIANCE'), ('GAME', 'VIDEO GAME')], default='LAPTOP', max_length=100),
            preserve_default=False,
        ),
    ]
