# Generated by Django 4.0.4 on 2022-07-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_category'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product',
        #     name='product_type',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        #     preserve_default=False,
        # ),
    ]
