# Generated by Django 4.0.4 on 2022-07-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_product_type'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='product_type',
        # ),
    ]
