# Generated by Django 4.0.4 on 2022-07-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_category_content_type_product_content_type_and_more'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='product',
        #     name='products_pr_content_7286c1_idx',
        # ),
    ]
