# Generated by Django 4.0.4 on 2022-07-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_products_pr_content_7286c1_idx'),
    ]

    operations = [
        # migrations.AddIndex(
        #     model_name='product',
        #     index=models.Index(fields=['content_type', 'object_id'], name='products_pr_content_7286c1_idx'),
        # ),
    ]
