# Generated by Django 4.0.4 on 2022-07-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_products_pr_content_7286c1_idx'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='product',
        #     name='products_pr_content_7286c1_idx',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='content_type',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='object_id',
        # ),
    ]
