# Generated by Django 4.0.4 on 2022-07-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0026_remove_product_products_pr_content_7286c1_idx_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product',
        #     name='content_type',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='object_id',
        #     field=models.PositiveIntegerField(default=1),
        #     preserve_default=False,
        # ),
        # migrations.AddIndex(
        #     model_name='product',
        #     index=models.Index(fields=['content_type', 'object_id'], name='products_pr_content_7286c1_idx'),
        # ),
    ]
