# Generated by Django 4.0.4 on 2022-07-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_gamegenres_game_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
    ]
