# Generated by Django 4.0.4 on 2022-07-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_game_genre'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='GameGenres',
        # ),
    ]
