# Generated by Django 4.0.4 on 2022-07-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_gamegenres_game_genre'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='GameGenres',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #     ],
        # ),
    ]
