# Generated by Django 4.0.4 on 2022-07-22 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_gamegenres_productreviews_review_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='user',
            new_name='reviewer',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
