# Generated by Django 4.0.4 on 2022-07-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_pc_manufacturer_alter_product_category_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='game',
        #     name='genre',
        # ),
    ]
