# Generated by Django 4.0.4 on 2022-07-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
