# Generated by Django 4.0.4 on 2022-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_product_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
