# Generated by Django 4.0.4 on 2022-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_product_category'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='category_id',
        # ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('PC', 'LAPTOP'), ('REFURBISHED', 'REFURBISHED PRODUCT'), ('ACCESSORY', 'TECH ACCESSORY'), ('APPLIANCE', 'OFFICE APPLIANCE'), ('GAME', 'VIDEO GAME')], default='PC', max_length=100),
        ),
    ]
