# Generated by Django 4.0.4 on 2022-07-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_category_category_products_ca_content_0b2c19_idx'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product',
        #     name='category_id',
        #     field=models.CharField(default='default', max_length=60),
        #     preserve_default=False,
        # ),
    ]
