# Generated by Django 4.0.4 on 2022-07-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_product_category_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='category_id',
        # ),
    ]
