# Generated by Django 4.0.4 on 2022-07-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_remove_product_category_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='category',
        #     name='content_type',
        # ),
        # migrations.RemoveIndex(
        #     model_name='product',
        #     name='products_pr_content_7286c1_idx',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='category',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='category_url',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='content_type',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='description',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='image',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='in_stock',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='name',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='object_id',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='percent_off',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='previous_price',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='price',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='slug',
        # ),
        # migrations.DeleteModel(
        #     name='Category',
        # ),
    ]
