# Generated by Django 4.0.4 on 2022-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_remove_category_content_type_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='game',
        #     name='product',
        # ),
        # migrations.RemoveField(
        #     model_name='moreproductimages',
        #     name='product',
        # ),
        # migrations.RemoveField(
        #     model_name='pc',
        #     name='product',
        # ),
        # migrations.RemoveField(
        #     model_name='phone',
        #     name='product',
        # ),
        # migrations.RemoveField(
        #     model_name='productreviews',
        #     name='product',
        # ),
        # migrations.AddField(
        #     model_name='game',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='pc',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='phone',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
