# Generated by Django 4.0.4 on 2022-07-23 17:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0047_remove_game_product_remove_moreproductimages_product_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='game',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='pc',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='phone',
        #     name='id',
        # ),
        # migrations.AddField(
        #     model_name='game',
        #     name='product',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_info', serialize=False, to='products.product'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='moreproductimages',
        #     name='product',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='pc',
        #     name='product',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pc_info', serialize=False, to='products.product'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='phone',
        #     name='product',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone_info', serialize=False, to='products.product'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='category',
        #     field=models.CharField(choices=[('PHONE', 'PHONE'), ('PC', 'LAPTOP'), ('REFURBISHED', 'REFURBISHED PRODUCT'), ('ACCESSORY', 'TECH ACCESSORY'), ('APPLIANCE', 'OFFICE APPLIANCE'), ('GAME', 'VIDEO GAME')], default='PC', max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='category_url',
        #     field=models.CharField(default='laptops', max_length=100),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='content_type',
        #     field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='description',
        #     field=ckeditor_uploader.fields.RichTextUploadingField(default='Described as here'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='image',
        #     field=models.ImageField(blank=True, upload_to='products_images/'),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='in_stock',
        #     field=models.BooleanField(default=True),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='name',
        #     field=models.CharField(default='Your Name', help_text='Name of Product', max_length=250),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='object_id',
        #     field=models.PositiveIntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='percent_off',
        #     field=models.IntegerField(default=2),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='previous_price',
        #     field=models.PositiveIntegerField(blank=True, default=0),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='price',
        #     field=models.PositiveIntegerField(default=19),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='slug',
        #     field=models.SlugField(auto_created=True, blank=True, max_length=300),
        # ),
        # migrations.AddField(
        #     model_name='productreviews',
        #     name='product',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        #     preserve_default=False,
        # ),
        # migrations.AddIndex(
        #     model_name='product',
        #     index=models.Index(fields=['content_type', 'object_id'], name='products_pr_content_7286c1_idx'),
        # ),
    ]
